STATUS_OPEN = 'open'
STATUS_CLOSED = 'closed'
DEFAULT_STATUS = STATUS_OPEN
STATUS_CHOICES = [
        (STATUS_OPEN, 'Открыт'),
        (STATUS_CLOSED, 'Закрыт'),
    ]
MAX_LENGTH_NAME_PROJECT = 200
MAX_LENGTH_STATUS_PROJECT = 6
